"""Generate src/theme-dark.css from the colours actually used in the JSX.

The UI uses Tailwind arbitrary colours (bg-[#f8f7f3], text-[#101828], ...).
Instead of editing hundreds of class lists, every (utility, colour) pair found
in src/ gets a dark-mode counterpart under `html.dark`:
  light backgrounds -> dark surfaces (tints keep a hint of their hue)
  dark text         -> light text      mid greys -> lighter greys
  light borders     -> dark borders    brand/status colours -> lightened
Already-dark backgrounds (navy buttons, sidebar) are left as they are.
Run:  python scripts/gen_dark_theme.py   (npm run theme:dark)
"""
import colorsys
import re
from pathlib import Path

SRC = Path(__file__).resolve().parents[1] / "src"
OUT = SRC / "theme-dark.css"
CLS = re.compile(r"((?:hover:|focus:)?)(bg|text|border|ring|divide|placeholder|from|to|via)-\[#([0-9a-fA-F]{3,8})\]")
BASE = (15, 23, 38)  # page background in dark mode


def rgb(h):
    h = h if len(h) == 6 else "".join(c * 2 for c in h[:3])
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def hexs(c):
    return "#%02x%02x%02x" % tuple(max(0, min(255, round(v))) for v in c)


def lum(c):
    return (0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]) / 255


def mix(a, b, t):
    return tuple(a[i] * (1 - t) + b[i] * t for i in range(3))


def sat(c):
    return colorsys.rgb_to_hls(*(v / 255 for v in c))[2]


def dark_bg(c):
    L = lum(c)
    if L < 0.45:
        return None  # already dark (navy buttons, sidebar)
    if sat(c) > 0.35 and L < 0.8:
        return None  # saturated accent (brand gold, status dots) keeps its colour
    if sat(c) > 0.25 and L < 0.97:
        return hexs(mix(BASE, c, 0.16))  # tinted panel keeps its hue
    # neutral surfaces: whiter source -> slightly raised surface
    return hexs(mix(BASE, (60, 72, 96), 0.35 + (1 - L) * 0.8))


def dark_text(c):
    L = lum(c)
    h, l, s = colorsys.rgb_to_hls(*(v / 255 for v in c))
    if s > 0.3 and 0.2 < L < 0.8:  # coloured text (green, red, gold, navy)
        r, g, b = colorsys.hls_to_rgb(h, min(0.78, l + 0.3), min(1, s))
        return hexs((r * 255, g * 255, b * 255))
    if L < 0.25:
        return "#e8ecf3"
    if L < 0.5:
        return "#c3cad6"
    if L < 0.7:
        return "#9aa5b8"
    return None  # light text on dark buttons stays


def dark_border(c):
    L = lum(c)
    if L < 0.5:
        return None
    if sat(c) > 0.35:
        return hexs(mix(BASE, c, 0.35))
    return "#2b3950"


def esc(cls):
    return re.sub(r"([\[\]#:])", r"\\\1", cls)


def main():
    pairs = set()
    for f in SRC.rglob("*.jsx"):
        if "__tests__" in f.parts:
            continue
        for pre, util, col in CLS.findall(f.read_text(encoding="utf-8")):
            pairs.add((pre, util, col))
    rules = []
    for pre, util, col in sorted(pairs):
        c = rgb(col)
        if util in ("bg", "from", "to", "via"):
            new, prop = dark_bg(c), "background-color"
        elif util == "text" or util == "placeholder":
            new, prop = dark_text(c), "color"
        else:
            new, prop = dark_border(c), "border-color" if util in ("border", "divide") else "--tw-ring-color"
        if not new:
            continue
        if util in ("from", "to", "via"):
            continue  # gradients are decorative; left untouched
        cls = f"{pre}{util}-[#{col}]"
        sel = f"html.dark .{esc(cls)}"
        if pre == "hover:":
            sel += ":hover"
        if pre == "focus:":
            sel += ":focus"
        if util == "placeholder":
            sel += "::placeholder"
        rules.append(f"{sel} {{ {prop}: {new}; }}")
    head = """/* Generated by scripts/gen_dark_theme.py — do not edit by hand. */
html.dark { color-scheme: dark; }
html.dark body { background-color: #0f1726; color: #e8ecf3; }
html.dark .bg-white { background-color: #172234; }
html.dark .border-white { border-color: #2b3950; }
html.dark .hover\\:bg-white:hover { background-color: #1d2a40; }
html.dark input, html.dark select, html.dark textarea { background-color: #111b2c; color: #e8ecf3; border-color: #2b3950; }
html.dark img { opacity: .92; }
"""
    OUT.write_text(head + "\n".join(rules) + "\n", encoding="utf-8")
    print(f"{len(rules)} dark rules from {len(pairs)} colour classes -> {OUT.name}")


if __name__ == "__main__":
    main()
